### ISSUE TITLE
time cheat on the clock in level 4 is not working

### ISSUE THREAD

**Issue by gabberhead** [MK1Roxxor/WHDLoad_Patches#1]
i played the game till the end. all is working now. except the time cheat on level 4. the time cheat on the clock is not working. after a full turn of the pointer on the clock, the level is over and the level must be starting from the beginning.

**Comment by MK1Roxxor** [comment]
Which game are you referring to?

**Comment by gabberhead** [comment]
Sorry. I mean back to the future ii.

**Comment by MK1Roxxor** [comment]
No problem, thanks for reporting, I will have a look and fix the unlimited time trainer for level 4.

**Comment by MK1Roxxor** [comment]
I have updated the patch to 1.3a, the unlimited time trainer works properly for level 4 now. Thanks for reporting.
